
name: DepthAI ROS Testing
on:
  workflow_dispatch:

env:
  ROS_DISTRO: kilted

jobs:
  run_vanilla_tests:
    uses: ./.github/workflows/test_child.yml
    secrets:
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      HIL_PAT_TOKEN: ${{ secrets.HIL_PAT_TOKEN }}